services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend_dev # Use the development stage
    ports:
      - '3015:3000' # Map backend's internal port 3000 to host's port 3015
    environment:
      NODE_ENV: development
      HOST_PORT: 3015 # Pass the host-mapped port for better logging
    volumes:
      - ./backend:/app/backend # Mount the local backend directory
      - /app/backend/node_modules # Prevent overwriting node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    command: npm run dev # Start backend with nodemon

  frontend:
    build:
      context: ./ # Build context is the root directory
      dockerfile: ui/Dockerfile # Dockerfile for frontend is inside ./ui
      target: ui-dev
    working_dir: /app/ui # Set the working directory to /app/ui
    ports:
      - '3044:3044' # Map frontend's internal port 3000 to host's port 3001
      - '3001:3000' # Serve built version of the app
    environment:
      NODE_ENV: development
      VITE_API_URL: http://backend:3000 # Access backend via host
    volumes:
      - ./ui:/app/ui:delegated # Mount the local frontend source code
    command: npm run dev # Use Vite for live reload

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile # Dockerfile is inside the prometheus directory
    ports:
      - '9094:9090' # Map Prometheus's internal port 9090 to host's port 9094
